version: '3.8'

services:
  app:
    image: pron1mo/crt:php

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
